name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch's name
  push:
    branches: [src]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install all fonts (concurrent)
        run: |
          sudo add-apt-repository universe -y
          sudo apt-get update

          # APT 装系统包
          sudo apt-get install -y fonts-noto-cjk-extra fonts-lmodern &

          # IBM Plex
          (
            curl -L https://github.com/IBM/plex/releases/download/%40ibm%2Fplex-sans-sc%401.1.0/ibm-plex-sans-sc.zip -o ibm-plex-sans-sc.zip
            unzip ibm-plex-sans-sc.zip -d ./fonts
            sudo mkdir -p /usr/share/fonts/truetype/ibm-plex
            find ./fonts/ibm-plex-sans-sc/fonts/complete/ttf -name "*.ttf" -exec sudo cp {} /usr/share/fonts/truetype/ibm-plex/ \;
          ) &

          # HarmonyOS Sans
          (
            git clone --depth=1 https://gitee.com/openharmony/utils_system_resources.git
            cd utils_system_resources/fonts
            sudo mkdir -p /usr/share/fonts/truetype/harmonyos
            find . -name "*.ttf" -exec sudo cp {} /usr/share/fonts/truetype/harmonyos/ \;
          ) &

          wait            # 等三条后台任务全部结束
          sudo fc-cache -f -v
          fc-list | grep -i "IBM Plex"
          fc-list | grep -i "Harmony"
      - name: Install, build, and upload my site
        uses: withastro/action@v4
        with:
          # path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 22 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
          package-manager: pnpm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
